
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 𝐙𝐚𝐥𝐥𝐤𝐲 𝐍𝐞𝐨
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        Connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel d;

    public void Connect() {
        try {
            Class.forName("org.h2.Driver");
            // Use absolute path passed from run script to avoid working-directory issues
            String dbPath = System.getProperty("db.path", "./data/schoolmanagment");
            System.out.println("Connecting to database at: " + dbPath);
            con = DriverManager.getConnection("jdbc:h2:" + dbPath + ";MODE=MySQL;AUTO_SERVER=TRUE", "sa", "");
            System.out.println("Database connected successfully.");

            // Always ensure tables exist (safe with IF NOT EXISTS)
            java.sql.Statement stmt = con.createStatement();
            stmt.execute("CREATE TABLE IF NOT EXISTS USERS (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), PHONE INT, ADDRESS VARCHAR(255), UNAME VARCHAR(255), PASSWORD VARCHAR(255), UTYPE VARCHAR(255))");
            stmt.execute("CREATE TABLE IF NOT EXISTS CLASS (CID INT PRIMARY KEY AUTO_INCREMENT, CLASSNAME VARCHAR(255), SECTION VARCHAR(255))");
            stmt.execute("CREATE TABLE IF NOT EXISTS SUBJECT (SID INT PRIMARY KEY AUTO_INCREMENT, SUBJECTNAME VARCHAR(255))");
            stmt.execute("CREATE TABLE IF NOT EXISTS STUDENT (STUDENTID INT PRIMARY KEY AUTO_INCREMENT, STNAME VARCHAR(255), PNAME VARCHAR(255), DOB DATE, GENDER VARCHAR(255), PHONE VARCHAR(255), ADDRESS VARCHAR(255), CLASS VARCHAR(255), SECTION VARCHAR(255))");
            stmt.execute("CREATE TABLE IF NOT EXISTS EXAM (EXAMID INT PRIMARY KEY AUTO_INCREMENT, EXAMNAME VARCHAR(255), DATE DATE, CLASS VARCHAR(255), SECTION VARCHAR(255), SUBJECT VARCHAR(255))");
            stmt.execute("CREATE TABLE IF NOT EXISTS MARKS (MARKID INT PRIMARY KEY AUTO_INCREMENT, STID INT, STNAME VARCHAR(255), CLASS VARCHAR(255), SUBJECT VARCHAR(255), MARKS INT)");

            // Seed all sample data only when USERS table is completely empty
            java.sql.ResultSet rsCheck = stmt.executeQuery("SELECT COUNT(*) FROM USERS");
            if (rsCheck.next() && rsCheck.getInt(1) == 0) {
                System.out.println("Empty database detected. Seeding sample data...");

                // ── USERS (Admin + Teachers) ──────────────────────────
                stmt.execute("INSERT INTO USERS (NAME,PHONE,ADDRESS,UNAME,PASSWORD,UTYPE) VALUES ('Amal Silva',715689652,'56/8A Yakkala, Gampaha','admin','admin','Admin')");
                stmt.execute("INSERT INTO USERS (NAME,PHONE,ADDRESS,UNAME,PASSWORD,UTYPE) VALUES ('Kasuni Perera',771234567,'12/B Kandy Road, Colombo','Kasuni','1234','Teacher')");
                stmt.execute("INSERT INTO USERS (NAME,PHONE,ADDRESS,UNAME,PASSWORD,UTYPE) VALUES ('Nimal Fernando',762345678,'34/C Galle Road, Matara','Nimal','1234','Teacher')");
                stmt.execute("INSERT INTO USERS (NAME,PHONE,ADDRESS,UNAME,PASSWORD,UTYPE) VALUES ('Sanduni Jayawardena',753456789,'78/D Negombo Road, Ja-Ela','Sanduni','1234','Teacher')");

                // ── CLASSES ────────────────────────────────────────────
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 6','A')");
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 6','B')");
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 7','A')");
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 7','B')");
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 8','A')");
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 8','B')");
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 9','A')");
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 9','B')");
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 10','A')");
                stmt.execute("INSERT INTO CLASS (CLASSNAME,SECTION) VALUES ('Grade 10','B')");

                // ── SUBJECTS ───────────────────────────────────────────
                stmt.execute("INSERT INTO SUBJECT (SUBJECTNAME) VALUES ('Mathematics')");
                stmt.execute("INSERT INTO SUBJECT (SUBJECTNAME) VALUES ('Science')");
                stmt.execute("INSERT INTO SUBJECT (SUBJECTNAME) VALUES ('English')");
                stmt.execute("INSERT INTO SUBJECT (SUBJECTNAME) VALUES ('Sinhala')");
                stmt.execute("INSERT INTO SUBJECT (SUBJECTNAME) VALUES ('History')");
                stmt.execute("INSERT INTO SUBJECT (SUBJECTNAME) VALUES ('ICT')");
                stmt.execute("INSERT INTO SUBJECT (SUBJECTNAME) VALUES ('Art')");
                stmt.execute("INSERT INTO SUBJECT (SUBJECTNAME) VALUES ('Health & PE')");

                // ── STUDENTS ───────────────────────────────────────────
                // Grade 6 - A
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Kavya Rathnayake','Sunil Rathnayake','2012-03-14','Female','0771110001','23 Lake Rd, Colombo','Grade 6','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Dineth Kumara','Pradeep Kumara','2012-07-22','Male','0772220002','45 Hill St, Kandy','Grade 6','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Shenal Wijesinghe','Rohan Wijesinghe','2012-11-05','Male','0773330003','67 Beach Ave, Galle','Grade 6','A')");
                // Grade 6 - B
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Amaya Dissanayake','Chaminda Dissanayake','2012-01-18','Female','0774440004','89 Park Ln, Negombo','Grade 6','B')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Thisara Jayasekara','Lasitha Jayasekara','2012-09-30','Male','0775550005','12 River Rd, Matale','Grade 6','B')");
                // Grade 7 - A
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Senuri Pathirana','Aruna Pathirana','2011-04-12','Female','0776660006','34 Temple Rd, Kurunegala','Grade 7','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Muditha Bandara','Gamini Bandara','2011-06-25','Male','0777770007','56 Main St, Anuradhapura','Grade 7','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Hasini Samarakoon','Upul Samarakoon','2011-12-08','Female','0778880008','78 Fort Rd, Trincomalee','Grade 7','A')");
                // Grade 7 - B
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Sachith Madushanka','Bandula Madushanka','2011-02-14','Male','0779990009','90 Galle Rd, Moratuwa','Grade 7','B')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Dilhara Weerasinghe','Ajith Weerasinghe','2011-08-19','Female','0770001010','11 Baseline Rd, Colombo 9','Grade 7','B')");
                // Grade 8 - A
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Pasindu Liyanage','Channa Liyanage','2010-05-27','Male','0771111011','22 Kandy Rd, Kegalle','Grade 8','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Thilini Gunasekara','Priya Gunasekara','2010-10-03','Female','0772222012','44 High Level Rd, Maharagama','Grade 8','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Ravindu Perera','Sanjeewa Perera','2010-03-16','Male','0773333013','66 Hospital Rd, Ratnapura','Grade 8','A')");
                // Grade 9 - A
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Ishara Wickramasinghe','Nalinda Wickramasinghe','2009-07-09','Female','0774444014','88 Matara Rd, Hambantota','Grade 9','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Dasun Rajapaksha','Ranjan Rajapaksha','2009-11-21','Male','0775555015','10 Pettah, Colombo 11','Grade 9','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Nimasha Chamara','Thilak Chamara','2009-01-30','Female','0776666016','32 Union Place, Colombo 2','Grade 9','A')");
                // Grade 10 - A
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Kasun Abeysekara','Manoj Abeysekara','2008-04-04','Male','0777777017','54 Flower Rd, Colombo 7','Grade 10','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Ridma Kariyawasam','Pradeep Kariyawasam','2008-09-13','Female','0778888018','76 Ward Place, Colombo 7','Grade 10','A')");
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Chanaka Madushan','Saman Madushan','2008-02-28','Male','0779999019','98 Duplication Rd, Colombo 3','Grade 10','A')");
                // Grade 10 - B
                stmt.execute("INSERT INTO STUDENT (STNAME,PNAME,DOB,GENDER,PHONE,ADDRESS,CLASS,SECTION) VALUES ('Ashini Rodrigo','Bertram Rodrigo','2008-06-17','Female','0770000020','20 Aloe Ave, Colombo 6','Grade 10','B')");

                // ── EXAMS ──────────────────────────────────────────────
                stmt.execute("INSERT INTO EXAM (EXAMNAME,DATE,CLASS,SECTION,SUBJECT) VALUES ('Term 1 Maths','2026-02-10','Grade 6','A','Mathematics')");
                stmt.execute("INSERT INTO EXAM (EXAMNAME,DATE,CLASS,SECTION,SUBJECT) VALUES ('Term 1 Science','2026-02-11','Grade 6','A','Science')");
                stmt.execute("INSERT INTO EXAM (EXAMNAME,DATE,CLASS,SECTION,SUBJECT) VALUES ('Term 1 Maths','2026-02-10','Grade 7','A','Mathematics')");
                stmt.execute("INSERT INTO EXAM (EXAMNAME,DATE,CLASS,SECTION,SUBJECT) VALUES ('Term 1 English','2026-02-12','Grade 7','A','English')");
                stmt.execute("INSERT INTO EXAM (EXAMNAME,DATE,CLASS,SECTION,SUBJECT) VALUES ('Mid Year Maths','2026-07-05','Grade 9','A','Mathematics')");
                stmt.execute("INSERT INTO EXAM (EXAMNAME,DATE,CLASS,SECTION,SUBJECT) VALUES ('Mid Year ICT','2026-07-06','Grade 10','A','ICT')");

                // ── MARKS ──────────────────────────────────────────────
                // Grade 6-A — Term 1 Maths (STID 1,2,3)
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (1,'Kavya Rathnayake','Grade 6','Mathematics',88)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (2,'Dineth Kumara','Grade 6','Mathematics',74)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (3,'Shenal Wijesinghe','Grade 6','Mathematics',91)");
                // Grade 6-A — Term 1 Science
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (1,'Kavya Rathnayake','Grade 6','Science',79)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (2,'Dineth Kumara','Grade 6','Science',65)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (3,'Shenal Wijesinghe','Grade 6','Science',83)");
                // Grade 7-A — Term 1 Maths (STID 6,7,8)
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (6,'Senuri Pathirana','Grade 7','Mathematics',95)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (7,'Muditha Bandara','Grade 7','Mathematics',68)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (8,'Hasini Samarakoon','Grade 7','Mathematics',82)");
                // Grade 7-A — Term 1 English
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (6,'Senuri Pathirana','Grade 7','English',88)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (7,'Muditha Bandara','Grade 7','English',71)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (8,'Hasini Samarakoon','Grade 7','English',90)");
                // Grade 9-A — Mid Year Maths (STID 14,15,16)
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (14,'Ishara Wickramasinghe','Grade 9','Mathematics',77)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (15,'Dasun Rajapaksha','Grade 9','Mathematics',84)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (16,'Nimasha Chamara','Grade 9','Mathematics',92)");
                // Grade 10-A — Mid Year ICT (STID 17,18,19)
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (17,'Kasun Abeysekara','Grade 10','ICT',85)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (18,'Ridma Kariyawasam','Grade 10','ICT',93)");
                stmt.execute("INSERT INTO MARKS (STID,STNAME,CLASS,SUBJECT,MARKS) VALUES (19,'Chanaka Madushan','Grade 10','ICT',70)");

                System.out.println("Sample data seeded successfully.");
            } else {
                System.out.println("Database tables ready.");
            }
            rsCheck.close();
            stmt.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            System.err.println("DATABASE ERROR: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, "Database Connection/Initialization Error: " + ex.getMessage());
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtutype = new javax.swing.JComboBox<>();
        txtuname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(246, 255, 244));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("User Type");

        txtutype.setBackground(new java.awt.Color(246, 255, 244));
        txtutype.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtutype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Teacher" }));

        txtuname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(26, 26, 26)
                        .addComponent(txtutype, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtuname, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(txtpass))))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtutype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 230, 300));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       loginToSystem();
//        testJasper();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuname;
    private javax.swing.JComboBox<String> txtutype;
    // End of variables declaration//GEN-END:variables

    private void testJasper() {
        
    }

    private void loginToSystem() {
        String username = txtuname.getText().trim();
        String pass = txtpass.getText().trim();
        String utype = txtutype.getSelectedItem().toString();

        try {
            if (con == null) {
                JOptionPane.showMessageDialog(this, "Database connection not established.");
                return;
            }
            System.out.println("Attempting login: user=" + username + ", type=" + utype);

            pst = con.prepareStatement("SELECT * FROM USERS WHERE UNAME = ? AND PASSWORD = ? AND UTYPE = ?");
            pst.setString(1, username);
            pst.setString(2, pass);
            pst.setString(3, utype);
            rs = pst.executeQuery();
            if (rs.next()) {
                System.out.println("Login successful!");
                int id = rs.getInt("ID");
                this.setVisible(false);

                if (utype.equals("Admin")) {
                    new main(id, username, utype).setVisible(true);
                } else if (utype.equals("Teacher")) {
                    new teachermain(id, username, utype).setVisible(true);
                }
            } else {
                System.out.println("Login failed: Invalid credentials.");
                JOptionPane.showMessageDialog(this, "Username or Password does not match!");
                txtuname.setText("");
                txtpass.setText("");
                txtuname.requestFocus();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            System.out.println("Login error: " + ex.getMessage());
            JOptionPane.showMessageDialog(this, "Login Error: " + ex.getMessage());
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
